// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef SILABS_THREAD_BOOKKEEPING_H
#define SILABS_THREAD_BOOKKEEPING_H


#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include EMBER_AF_API_STACK
#include EMBER_AF_API_ZCL_CORE

bool emberAfOkToSleep(uint32_t durationMs);

void emberAfPluginIdleSleepWakeUp(uint32_t durationMs);

bool emberAfOkToIdle(uint32_t durationMs);

void emberAfPluginIdleSleepActive(uint32_t durationMs);

void emAfMain(MAIN_FUNCTION_PARAMETERS);

void emAfInit(void);

void emAfTick(void);

void emAfMarkApplicationBuffers(void);

void emberNetworkStatusHandler(EmberNetworkStatus newNetworkStatus, EmberNetworkStatus oldNetworkStatus, EmberJoinFailureReason reason);

bool emZclPreAttributeChange(EmberZclEndpointId_t endpointId, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);

void emZclPostAttributeChange(EmberZclEndpointId_t endpointId, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);

void emZclNotification(const EmberZclNotificationContext_t *context, const EmberZclClusterSpec_t *clusterSpec, EmberZclAttributeId_t attributeId, const void *buffer, size_t bufferLength);

#endif // SILABS_THREAD_BOOKKEEPING_H
