// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the static data to populate all ZCL structs for the configured device.
#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include EMBER_AF_API_ZCL_CORE
#include "thread-callbacks.h"

// -----------------------------------------------------------------------------
// Basic cluster (0x0000).

// Basic cluster client (0x0000).
const EmberZclClusterSpec_t emberZclClusterBasicClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_BASIC,
};

// Basic cluster server (0x0000).
const EmberZclClusterSpec_t emberZclClusterBasicServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_BASIC,
};

// Basic cluster server (0x0000) - ResetToFactoryDefaults (0x00) command.
#define emZclClusterBasicServerCommandResetToFactoryDefaultsRequestSpec NULL
static const ZclipStructSpec emZclClusterBasicServerCommandResetToFactoryDefaultsResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterBasicServerCommandResetToFactoryDefaultsResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterBasicServerCommandResetToFactoryDefaultsResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterBasicServerCommandResetToFactoryDefaultsResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterBasicServerCommandResetToFactoryDefaultsResponseSpec);
}

// -----------------------------------------------------------------------------
// Identify cluster (0x0003).

// Identify cluster client (0x0003).
const EmberZclClusterSpec_t emberZclClusterIdentifyClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_IDENTIFY,
};

// Identify cluster server (0x0003).
const EmberZclClusterSpec_t emberZclClusterIdentifyServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_IDENTIFY,
};

// Identify cluster server (0x0003) - Identify (0x00) command.
static const ZclipStructSpec emZclClusterIdentifyServerCommandIdentifyRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandIdentifyRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, identifyTime),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterIdentifyServerCommandIdentifyResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandIdentifyResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterIdentifyServerCommandIdentifyRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterIdentifyServerCommandIdentifyRequest_t *request,
  const EmberZclClusterIdentifyServerCommandIdentifyResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterIdentifyServerSpec,
                                 EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_IDENTIFY,
                                 request,
                                 emZclClusterIdentifyServerCommandIdentifyRequestSpec,
                                 emZclClusterIdentifyServerCommandIdentifyResponseSpec,
                                 (EmZclResponseHandler)handler);
}
void emZclCliClusterIdentifyServerCommandIdentifyRequestCommand(void)
{
  emZclCliSetCurrentRequestCommand(&emberZclClusterIdentifyServerSpec,
                                   EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_IDENTIFY,
                                   emZclClusterIdentifyServerCommandIdentifyRequestSpec,
                                   (EmZclCliRequestCommandFunction)emberZclSendClusterIdentifyServerCommandIdentifyRequest,
                                   "v");
}
EmberStatus emberZclSendClusterIdentifyServerCommandIdentifyResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterIdentifyServerCommandIdentifyResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterIdentifyServerCommandIdentifyResponseSpec);
}

// Identify cluster server (0x0003) - IdentifyQuery (0x01) command.
#define emZclClusterIdentifyServerCommandIdentifyQueryRequestSpec NULL
static const ZclipStructSpec emZclClusterIdentifyServerCommandIdentifyQueryResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandIdentifyQueryResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, timeout),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterIdentifyServerCommandIdentifyQueryRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterIdentifyServerCommandIdentifyQueryRequest_t *request,
  const EmberZclClusterIdentifyServerCommandIdentifyQueryResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterIdentifyServerSpec,
                                 EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_IDENTIFY_QUERY,
                                 request,
                                 emZclClusterIdentifyServerCommandIdentifyQueryRequestSpec,
                                 emZclClusterIdentifyServerCommandIdentifyQueryResponseSpec,
                                 (EmZclResponseHandler)handler);
}
void emZclCliClusterIdentifyServerCommandIdentifyQueryRequestCommand(void)
{
  emZclCliSetCurrentRequestCommand(&emberZclClusterIdentifyServerSpec,
                                   EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_IDENTIFY_QUERY,
                                   emZclClusterIdentifyServerCommandIdentifyQueryRequestSpec,
                                   (EmZclCliRequestCommandFunction)emberZclSendClusterIdentifyServerCommandIdentifyQueryRequest,
                                   "");
}
EmberStatus emberZclSendClusterIdentifyServerCommandIdentifyQueryResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterIdentifyServerCommandIdentifyQueryResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterIdentifyServerCommandIdentifyQueryResponseSpec);
}

// Identify cluster server (0x0003) - EZModeInvoke (0x02) command.
static const ZclipStructSpec emZclClusterIdentifyServerCommandEZModeInvokeRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandEZModeInvokeRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, action),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterIdentifyServerCommandEZModeInvokeResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandEZModeInvokeResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterIdentifyServerCommandEZModeInvokeRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterIdentifyServerCommandEZModeInvokeRequest_t *request,
  const EmberZclClusterIdentifyServerCommandEZModeInvokeResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterIdentifyServerSpec,
                                 EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_E_Z_MODE_INVOKE,
                                 request,
                                 emZclClusterIdentifyServerCommandEZModeInvokeRequestSpec,
                                 emZclClusterIdentifyServerCommandEZModeInvokeResponseSpec,
                                 (EmZclResponseHandler)handler);
}
void emZclCliClusterIdentifyServerCommandEZModeInvokeRequestCommand(void)
{
  emZclCliSetCurrentRequestCommand(&emberZclClusterIdentifyServerSpec,
                                   EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_E_Z_MODE_INVOKE,
                                   emZclClusterIdentifyServerCommandEZModeInvokeRequestSpec,
                                   (EmZclCliRequestCommandFunction)emberZclSendClusterIdentifyServerCommandEZModeInvokeRequest,
                                   "u");
}
EmberStatus emberZclSendClusterIdentifyServerCommandEZModeInvokeResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterIdentifyServerCommandEZModeInvokeResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterIdentifyServerCommandEZModeInvokeResponseSpec);
}

// Identify cluster server (0x0003) - UpdateCommissionState (0x03) command.
static const ZclipStructSpec emZclClusterIdentifyServerCommandUpdateCommissionStateRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandUpdateCommissionStateRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, action),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, commissionStateMask),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterIdentifyServerCommandUpdateCommissionStateResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandUpdateCommissionStateResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterIdentifyServerCommandUpdateCommissionStateRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterIdentifyServerCommandUpdateCommissionStateRequest_t *request,
  const EmberZclClusterIdentifyServerCommandUpdateCommissionStateResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterIdentifyServerSpec,
                                 EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_UPDATE_COMMISSION_STATE,
                                 request,
                                 emZclClusterIdentifyServerCommandUpdateCommissionStateRequestSpec,
                                 emZclClusterIdentifyServerCommandUpdateCommissionStateResponseSpec,
                                 (EmZclResponseHandler)handler);
}
EmberStatus emberZclSendClusterIdentifyServerCommandUpdateCommissionStateResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterIdentifyServerCommandUpdateCommissionStateResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterIdentifyServerCommandUpdateCommissionStateResponseSpec);
}

// Identify cluster server (0x0003) - TriggerEffect (0x40) command.
static const ZclipStructSpec emZclClusterIdentifyServerCommandTriggerEffectRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandTriggerEffectRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, effectId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, effectVariant),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterIdentifyServerCommandTriggerEffectResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterIdentifyServerCommandTriggerEffectResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterIdentifyServerCommandTriggerEffectRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterIdentifyServerCommandTriggerEffectRequest_t *request,
  const EmberZclClusterIdentifyServerCommandTriggerEffectResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterIdentifyServerSpec,
                                 EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_TRIGGER_EFFECT,
                                 request,
                                 emZclClusterIdentifyServerCommandTriggerEffectRequestSpec,
                                 emZclClusterIdentifyServerCommandTriggerEffectResponseSpec,
                                 (EmZclResponseHandler)handler);
}
void emZclCliClusterIdentifyServerCommandTriggerEffectRequestCommand(void)
{
  emZclCliSetCurrentRequestCommand(&emberZclClusterIdentifyServerSpec,
                                   EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_TRIGGER_EFFECT,
                                   emZclClusterIdentifyServerCommandTriggerEffectRequestSpec,
                                   (EmZclCliRequestCommandFunction)emberZclSendClusterIdentifyServerCommandTriggerEffectRequest,
                                   "uu");
}
EmberStatus emberZclSendClusterIdentifyServerCommandTriggerEffectResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterIdentifyServerCommandTriggerEffectResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterIdentifyServerCommandTriggerEffectResponseSpec);
}

// -----------------------------------------------------------------------------
// On/off cluster (0x0006).

// On/off cluster client (0x0006).
const EmberZclClusterSpec_t emberZclClusterOnOffClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_ON_OFF,
};

// On/off cluster server (0x0006).
const EmberZclClusterSpec_t emberZclClusterOnOffServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_ON_OFF,
};

// On/off cluster server (0x0006) - Off (0x00) command.
#define emZclClusterOnOffServerCommandOffRequestSpec NULL
static const ZclipStructSpec emZclClusterOnOffServerCommandOffResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOffResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandOffRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOnOffServerCommandOffRequest_t *request,
  const EmberZclClusterOnOffServerCommandOffResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOnOffServerSpec,
                                 EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_OFF,
                                 request,
                                 emZclClusterOnOffServerCommandOffRequestSpec,
                                 emZclClusterOnOffServerCommandOffResponseSpec,
                                 (EmZclResponseHandler)handler);
}
void emZclCliClusterOnOffServerCommandOffRequestCommand(void)
{
  emZclCliSetCurrentRequestCommand(&emberZclClusterOnOffServerSpec,
                                   EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_OFF,
                                   emZclClusterOnOffServerCommandOffRequestSpec,
                                   (EmZclCliRequestCommandFunction)emberZclSendClusterOnOffServerCommandOffRequest,
                                   "");
}
EmberStatus emberZclSendClusterOnOffServerCommandOffResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandOffResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandOffResponseSpec);
}

// On/off cluster server (0x0006) - On (0x01) command.
#define emZclClusterOnOffServerCommandOnRequestSpec NULL
static const ZclipStructSpec emZclClusterOnOffServerCommandOnResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOnResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandOnRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOnOffServerCommandOnRequest_t *request,
  const EmberZclClusterOnOffServerCommandOnResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOnOffServerSpec,
                                 EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON,
                                 request,
                                 emZclClusterOnOffServerCommandOnRequestSpec,
                                 emZclClusterOnOffServerCommandOnResponseSpec,
                                 (EmZclResponseHandler)handler);
}
void emZclCliClusterOnOffServerCommandOnRequestCommand(void)
{
  emZclCliSetCurrentRequestCommand(&emberZclClusterOnOffServerSpec,
                                   EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON,
                                   emZclClusterOnOffServerCommandOnRequestSpec,
                                   (EmZclCliRequestCommandFunction)emberZclSendClusterOnOffServerCommandOnRequest,
                                   "");
}
EmberStatus emberZclSendClusterOnOffServerCommandOnResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandOnResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandOnResponseSpec);
}

// On/off cluster server (0x0006) - Toggle (0x02) command.
#define emZclClusterOnOffServerCommandToggleRequestSpec NULL
static const ZclipStructSpec emZclClusterOnOffServerCommandToggleResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandToggleResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandToggleRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOnOffServerCommandToggleRequest_t *request,
  const EmberZclClusterOnOffServerCommandToggleResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOnOffServerSpec,
                                 EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_TOGGLE,
                                 request,
                                 emZclClusterOnOffServerCommandToggleRequestSpec,
                                 emZclClusterOnOffServerCommandToggleResponseSpec,
                                 (EmZclResponseHandler)handler);
}
void emZclCliClusterOnOffServerCommandToggleRequestCommand(void)
{
  emZclCliSetCurrentRequestCommand(&emberZclClusterOnOffServerSpec,
                                   EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_TOGGLE,
                                   emZclClusterOnOffServerCommandToggleRequestSpec,
                                   (EmZclCliRequestCommandFunction)emberZclSendClusterOnOffServerCommandToggleRequest,
                                   "");
}
EmberStatus emberZclSendClusterOnOffServerCommandToggleResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandToggleResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandToggleResponseSpec);
}

// On/off cluster server (0x0006) - OffWithEffect (0x40) command.
static const ZclipStructSpec emZclClusterOnOffServerCommandOffWithEffectRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOffWithEffectRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 2, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, effectId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, effectVariant),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOnOffServerCommandOffWithEffectResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOffWithEffectResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandOffWithEffectRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOnOffServerCommandOffWithEffectRequest_t *request,
  const EmberZclClusterOnOffServerCommandOffWithEffectResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOnOffServerSpec,
                                 EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_OFF_WITH_EFFECT,
                                 request,
                                 emZclClusterOnOffServerCommandOffWithEffectRequestSpec,
                                 emZclClusterOnOffServerCommandOffWithEffectResponseSpec,
                                 (EmZclResponseHandler)handler);
}
void emZclCliClusterOnOffServerCommandOffWithEffectRequestCommand(void)
{
  emZclCliSetCurrentRequestCommand(&emberZclClusterOnOffServerSpec,
                                   EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_OFF_WITH_EFFECT,
                                   emZclClusterOnOffServerCommandOffWithEffectRequestSpec,
                                   (EmZclCliRequestCommandFunction)emberZclSendClusterOnOffServerCommandOffWithEffectRequest,
                                   "uu");
}
EmberStatus emberZclSendClusterOnOffServerCommandOffWithEffectResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandOffWithEffectResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandOffWithEffectResponseSpec);
}

// On/off cluster server (0x0006) - OnWithRecallGlobalScene (0x41) command.
#define emZclClusterOnOffServerCommandOnWithRecallGlobalSceneRequestSpec NULL
static const ZclipStructSpec emZclClusterOnOffServerCommandOnWithRecallGlobalSceneResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOnWithRecallGlobalSceneResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandOnWithRecallGlobalSceneRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOnOffServerCommandOnWithRecallGlobalSceneRequest_t *request,
  const EmberZclClusterOnOffServerCommandOnWithRecallGlobalSceneResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOnOffServerSpec,
                                 EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON_WITH_RECALL_GLOBAL_SCENE,
                                 request,
                                 emZclClusterOnOffServerCommandOnWithRecallGlobalSceneRequestSpec,
                                 emZclClusterOnOffServerCommandOnWithRecallGlobalSceneResponseSpec,
                                 (EmZclResponseHandler)handler);
}
void emZclCliClusterOnOffServerCommandOnWithRecallGlobalSceneRequestCommand(void)
{
  emZclCliSetCurrentRequestCommand(&emberZclClusterOnOffServerSpec,
                                   EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON_WITH_RECALL_GLOBAL_SCENE,
                                   emZclClusterOnOffServerCommandOnWithRecallGlobalSceneRequestSpec,
                                   (EmZclCliRequestCommandFunction)emberZclSendClusterOnOffServerCommandOnWithRecallGlobalSceneRequest,
                                   "");
}
EmberStatus emberZclSendClusterOnOffServerCommandOnWithRecallGlobalSceneResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandOnWithRecallGlobalSceneResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandOnWithRecallGlobalSceneResponseSpec);
}

// On/off cluster server (0x0006) - OnWithTimedOff (0x42) command.
static const ZclipStructSpec emZclClusterOnOffServerCommandOnWithTimedOffRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOnWithTimedOffRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 3, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, onOffControl),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, onTime),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, offWaitTime),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOnOffServerCommandOnWithTimedOffResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOnOffServerCommandOnWithTimedOffResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOnOffServerCommandOnWithTimedOffRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOnOffServerCommandOnWithTimedOffRequest_t *request,
  const EmberZclClusterOnOffServerCommandOnWithTimedOffResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOnOffServerSpec,
                                 EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON_WITH_TIMED_OFF,
                                 request,
                                 emZclClusterOnOffServerCommandOnWithTimedOffRequestSpec,
                                 emZclClusterOnOffServerCommandOnWithTimedOffResponseSpec,
                                 (EmZclResponseHandler)handler);
}
void emZclCliClusterOnOffServerCommandOnWithTimedOffRequestCommand(void)
{
  emZclCliSetCurrentRequestCommand(&emberZclClusterOnOffServerSpec,
                                   EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON_WITH_TIMED_OFF,
                                   emZclClusterOnOffServerCommandOnWithTimedOffRequestSpec,
                                   (EmZclCliRequestCommandFunction)emberZclSendClusterOnOffServerCommandOnWithTimedOffRequest,
                                   "uvv");
}
EmberStatus emberZclSendClusterOnOffServerCommandOnWithTimedOffResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOnOffServerCommandOnWithTimedOffResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOnOffServerCommandOnWithTimedOffResponseSpec);
}

// -----------------------------------------------------------------------------
// Over the Air Bootloading cluster (0x0019).

// Over the Air Bootloading cluster client (0x0019).
const EmberZclClusterSpec_t emberZclClusterOtaBootloadClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_OTA_BOOTLOAD,
};

// Over the Air Bootloading cluster client (0x0019) - ImageNotify (0x00) command.
static const ZclipStructSpec emZclClusterOtaBootloadClientCommandImageNotifyRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadClientCommandImageNotifyRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, payloadType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, queryJitter),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, newFileVersion),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadClientCommandImageNotifyResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadClientCommandImageNotifyResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadClientCommandImageNotifyResponse(
  const EmberZclCommandContext_t *context,
  const EmberZclClusterOtaBootloadClientCommandImageNotifyResponse_t *response)
{
  return emZclSendCommandResponse(context,
                                  response,
                                  emZclClusterOtaBootloadClientCommandImageNotifyResponseSpec);
}

// Over the Air Bootloading cluster server (0x0019).
const EmberZclClusterSpec_t emberZclClusterOtaBootloadServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_OTA_BOOTLOAD,
};

// Over the Air Bootloading cluster server (0x0019) - QueryNextImageRequest (0x01) command.
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandQueryNextImageRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandQueryNextImageRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fieldControl),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, currentFileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, hardwareVersion),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandQueryNextImageResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandQueryNextImageResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageSize),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadServerCommandQueryNextImageRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOtaBootloadServerCommandQueryNextImageRequest_t *request,
  const EmberZclClusterOtaBootloadServerCommandQueryNextImageResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOtaBootloadServerSpec,
                                 EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_COMMAND_QUERY_NEXT_IMAGE_REQUEST,
                                 request,
                                 emZclClusterOtaBootloadServerCommandQueryNextImageRequestSpec,
                                 emZclClusterOtaBootloadServerCommandQueryNextImageResponseSpec,
                                 (EmZclResponseHandler)handler);
}

// Over the Air Bootloading cluster server (0x0019) - ImageBlockRequest (0x03) command.
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandImageBlockRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandImageBlockRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 7, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fieldControl),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileOffset),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, maxDataSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_BINARY, requestNodeAddress),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandImageBlockResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandImageBlockResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 7, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileOffset),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, dataSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageData),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadServerCommandImageBlockRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOtaBootloadServerCommandImageBlockRequest_t *request,
  const EmberZclClusterOtaBootloadServerCommandImageBlockResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOtaBootloadServerSpec,
                                 EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_COMMAND_IMAGE_BLOCK_REQUEST,
                                 request,
                                 emZclClusterOtaBootloadServerCommandImageBlockRequestSpec,
                                 emZclClusterOtaBootloadServerCommandImageBlockResponseSpec,
                                 (EmZclResponseHandler)handler);
}

// Over the Air Bootloading cluster server (0x0019) - ImagePageRequest (0x04) command.
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandImagePageRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandImagePageRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 9, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fieldControl),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileOffset),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, maxDataSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, pageSize),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, responseSpacing),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_BINARY, requestNodeAddress),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandImagePageResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandImagePageResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 1, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadServerCommandImagePageRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOtaBootloadServerCommandImagePageRequest_t *request,
  const EmberZclClusterOtaBootloadServerCommandImagePageResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOtaBootloadServerSpec,
                                 EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_COMMAND_IMAGE_PAGE_REQUEST,
                                 request,
                                 emZclClusterOtaBootloadServerCommandImagePageRequestSpec,
                                 emZclClusterOtaBootloadServerCommandImagePageResponseSpec,
                                 (EmZclResponseHandler)handler);
}

// Over the Air Bootloading cluster server (0x0019) - UpgradeEndRequest (0x06) command.
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandUpgradeEndRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandUpgradeEndRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 4, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandUpgradeEndResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandUpgradeEndResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, currentTime),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, upgradeTime),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadServerCommandUpgradeEndRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOtaBootloadServerCommandUpgradeEndRequest_t *request,
  const EmberZclClusterOtaBootloadServerCommandUpgradeEndResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOtaBootloadServerSpec,
                                 EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_COMMAND_UPGRADE_END_REQUEST,
                                 request,
                                 emZclClusterOtaBootloadServerCommandUpgradeEndRequestSpec,
                                 emZclClusterOtaBootloadServerCommandUpgradeEndResponseSpec,
                                 (EmZclResponseHandler)handler);
}

// Over the Air Bootloading cluster server (0x0019) - QuerySpecificFileRequest (0x08) command.
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandQuerySpecificFileRequestSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandQuerySpecificFileRequest_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_BINARY, requestNodeAddress),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, currentZigbeeStackVersion),
  #undef EMBER_ZCLIP_STRUCT
};
static const ZclipStructSpec emZclClusterOtaBootloadServerCommandQuerySpecificFileResponseSpec[] = {
  #define EMBER_ZCLIP_STRUCT EmberZclClusterOtaBootloadServerCommandQuerySpecificFileResponse_t
  EMBER_ZCLIP_OBJECT(sizeof(EMBER_ZCLIP_STRUCT), 5, NULL),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, status),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, manufacturerId),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageType),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, fileVersion),
  EMBER_ZCLIP_FIELD(EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER, imageSize),
  #undef EMBER_ZCLIP_STRUCT
};
EmberStatus emberZclSendClusterOtaBootloadServerCommandQuerySpecificFileRequest(
  const EmberZclDestination_t *destination,
  const EmberZclClusterOtaBootloadServerCommandQuerySpecificFileRequest_t *request,
  const EmberZclClusterOtaBootloadServerCommandQuerySpecificFileResponseHandler handler)
{
  return emZclSendCommandRequest(destination,
                                 &emberZclClusterOtaBootloadServerSpec,
                                 EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_COMMAND_QUERY_SPECIFIC_FILE_REQUEST,
                                 request,
                                 emZclClusterOtaBootloadServerCommandQuerySpecificFileRequestSpec,
                                 emZclClusterOtaBootloadServerCommandQuerySpecificFileResponseSpec,
                                 (EmZclResponseHandler)handler);
}

// -----------------------------------------------------------------------------
// Temperature Measurement cluster (0x0402).

// Temperature Measurement cluster client (0x0402).
const EmberZclClusterSpec_t emberZclClusterTempMeasurementClientSpec = {
  EMBER_ZCL_ROLE_CLIENT,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_TEMP_MEASUREMENT,
};

// Temperature Measurement cluster server (0x0402).
const EmberZclClusterSpec_t emberZclClusterTempMeasurementServerSpec = {
  EMBER_ZCL_ROLE_SERVER,
  EMBER_ZCL_MANUFACTURER_CODE_NULL,
  EMBER_ZCL_CLUSTER_TEMP_MEASUREMENT,
};

// -----------------------------------------------------------------------------
// Endpoints.

// Endpoint specs.
static const EmberZclClusterSpec_t *emZclEndpointPrimarySpec[] = {
  &emberZclClusterIdentifyClientSpec,
  &emberZclClusterOnOffClientSpec,
  &emberZclClusterOtaBootloadClientSpec,
  &emberZclClusterBasicServerSpec,
  &emberZclClusterIdentifyServerSpec,
  &emberZclClusterOnOffServerSpec,
  &emberZclClusterTempMeasurementServerSpec,
  NULL,
};

// Endpoint entries.
const EmZclEndpointEntry_t emZclEndpointTable[] = {
  {1, 0x0000, emZclEndpointPrimarySpec},
};
const size_t emZclEndpointCount = COUNTOF(emZclEndpointTable);

// -----------------------------------------------------------------------------
// Attributes.

// Attribute default, minimum, and maximum data.
const uint8_t emZclAttributeDefaultMinMaxData[] = {
#if BIGENDIAN_CPU
  0x00, 0x01,
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
  0xFF, 0xFF, 0xFF, 0xFF,
  0x02,
#else
  0x01, 0x00,
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
  0xFF, 0xFF, 0xFF, 0xFF,
  0x02,
#endif
};

// Attribute default, minimum, and maximum lookup table.
const size_t emZclAttributeDefaultMinMaxLookupTable[] = {
  0, // EMBER_ZCL_CLUSTER_IDENTIFY_CLIENT_ATTRIBUTE_IDENTIFY_CLUSTER_CLUSTER_REVISION_CLIENT: +DEFAULT, -MINIMUM, -MAXIMUM,
  0, // EMBER_ZCL_CLUSTER_ON_OFF_CLIENT_ATTRIBUTE_ON_OFF_CLUSTER_CLUSTER_REVISION_CLIENT: +DEFAULT, -MINIMUM, -MAXIMUM,
  2, // EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_UPGRADE_SERVER_ID: +DEFAULT, -MINIMUM, -MAXIMUM,
  10, // EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_FILE_OFFSET: +DEFAULT, -MINIMUM, -MAXIMUM,
  0, // EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_OTA_BOOTLOAD_CLUSTER_CLUSTER_REVISION_CLIENT: +DEFAULT, -MINIMUM, -MAXIMUM,
  14, // EMBER_ZCL_CLUSTER_BASIC_SERVER_ATTRIBUTE_VERSION: +DEFAULT, -MINIMUM, -MAXIMUM,
  0, // EMBER_ZCL_CLUSTER_BASIC_SERVER_ATTRIBUTE_BASIC_CLUSTER_CLUSTER_REVISION_SERVER: +DEFAULT, -MINIMUM, -MAXIMUM,
  0, // EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_ATTRIBUTE_IDENTIFY_CLUSTER_CLUSTER_REVISION_SERVER: +DEFAULT, -MINIMUM, -MAXIMUM,
  0, // EMBER_ZCL_CLUSTER_ON_OFF_SERVER_ATTRIBUTE_ON_OFF_CLUSTER_CLUSTER_REVISION_SERVER: +DEFAULT, -MINIMUM, -MAXIMUM,
  0, // EMBER_ZCL_CLUSTER_TEMP_MEASUREMENT_SERVER_ATTRIBUTE_TEMP_MEASUREMENT_CLUSTER_CLUSTER_REVISION_SERVER: +DEFAULT, -MINIMUM, -MAXIMUM,
};

// Attribute entries.
const EmZclAttributeEntry_t emZclAttributeTable[] = {
  {&emberZclClusterBasicClientSpec, EMBER_ZCL_CLUSTER_BASIC_CLIENT_ATTRIBUTE_BASIC_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 0, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterBasicClientSpec, EMBER_ZCL_CLUSTER_BASIC_CLIENT_ATTRIBUTE_BASIC_CLUSTER_REPORTING_STATUS_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 0, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterIdentifyClientSpec, EMBER_ZCL_CLUSTER_IDENTIFY_CLIENT_ATTRIBUTE_IDENTIFY_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 0, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterIdentifyClientSpec, EMBER_ZCL_CLUSTER_IDENTIFY_CLIENT_ATTRIBUTE_IDENTIFY_CLUSTER_REPORTING_STATUS_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 2, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOnOffClientSpec, EMBER_ZCL_CLUSTER_ON_OFF_CLIENT_ATTRIBUTE_ON_OFF_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 2, 1, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOnOffClientSpec, EMBER_ZCL_CLUSTER_ON_OFF_CLIENT_ATTRIBUTE_ON_OFF_CLUSTER_REPORTING_STATUS_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 4, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOtaBootloadClientSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_UPGRADE_SERVER_ID, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT, 4, 2, 8, EMBER_ZCLIP_TYPE_BINARY},
  {&emberZclClusterOtaBootloadClientSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_FILE_OFFSET, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 12, 3, 4, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOtaBootloadClientSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_IMAGE_UPGRADE_STATUS, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE, 16, 4, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOtaBootloadClientSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_ATTRIBUTE_OTA_BOOTLOAD_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 17, 4, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterTempMeasurementClientSpec, EMBER_ZCL_CLUSTER_TEMP_MEASUREMENT_CLIENT_ATTRIBUTE_TEMP_MEASUREMENT_CLUSTER_CLUSTER_REVISION_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 19, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterTempMeasurementClientSpec, EMBER_ZCL_CLUSTER_TEMP_MEASUREMENT_CLIENT_ATTRIBUTE_TEMP_MEASUREMENT_CLUSTER_REPORTING_STATUS_CLIENT, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 19, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterBasicServerSpec, EMBER_ZCL_CLUSTER_BASIC_SERVER_ATTRIBUTE_VERSION, EM_ZCL_ATTRIBUTE_STORAGE_SINGLETON_MASK|EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 19, 5, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterBasicServerSpec, EMBER_ZCL_CLUSTER_BASIC_SERVER_ATTRIBUTE_POWER_SOURCE, EM_ZCL_ATTRIBUTE_STORAGE_SINGLETON_MASK|EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE, 20, 6, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterBasicServerSpec, EMBER_ZCL_CLUSTER_BASIC_SERVER_ATTRIBUTE_BASIC_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_SINGLETON_MASK|EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 21, 6, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_ATTRIBUTE_IDENTIFY_TIME, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_ACCESS_WRITABLE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 23, 7, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_ATTRIBUTE_COMMISSION_STATE, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 25, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_ATTRIBUTE_IDENTIFY_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 25, 7, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_ATTRIBUTE_IDENTIFY_CLUSTER_REPORTING_STATUS_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 27, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_ATTRIBUTE_ON_OFF, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_ACCESS_REPORTABLE, 27, 8, 1, EMBER_ZCLIP_TYPE_BOOLEAN},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_ATTRIBUTE_GLOBAL_SCENE_CONTROL, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 28, 0, 1, EMBER_ZCLIP_TYPE_BOOLEAN},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_ATTRIBUTE_ON_TIME, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 28, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_ATTRIBUTE_OFF_WAIT_TIME, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 28, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_ATTRIBUTE_START_UP_ON_OFF, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 28, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_ATTRIBUTE_ON_OFF_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 28, 8, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_ATTRIBUTE_ON_OFF_CLUSTER_REPORTING_STATUS_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 30, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOtaBootloadServerSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_ATTRIBUTE_OTA_BOOTLOAD_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_NONE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 30, 0, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterOtaBootloadServerSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_SERVER_ATTRIBUTE_OTA_BOOTLOAD_CLUSTER_REPORTING_STATUS_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_NONE, 30, 0, 1, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
  {&emberZclClusterTempMeasurementServerSpec, EMBER_ZCL_CLUSTER_TEMP_MEASUREMENT_SERVER_ATTRIBUTE_TEMP_MEASURED_VALUE, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_ACCESS_REPORTABLE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 30, 9, 2, EMBER_ZCLIP_TYPE_INTEGER},
  {&emberZclClusterTempMeasurementServerSpec, EMBER_ZCL_CLUSTER_TEMP_MEASUREMENT_SERVER_ATTRIBUTE_TEMP_MIN_MEASURED_VALUE, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 32, 9, 2, EMBER_ZCLIP_TYPE_INTEGER},
  {&emberZclClusterTempMeasurementServerSpec, EMBER_ZCL_CLUSTER_TEMP_MEASUREMENT_SERVER_ATTRIBUTE_TEMP_MAX_MEASURED_VALUE, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 34, 9, 2, EMBER_ZCLIP_TYPE_INTEGER},
  {&emberZclClusterTempMeasurementServerSpec, EMBER_ZCL_CLUSTER_TEMP_MEASUREMENT_SERVER_ATTRIBUTE_TEMP_MEASUREMENT_CLUSTER_CLUSTER_REVISION_SERVER, EM_ZCL_ATTRIBUTE_STORAGE_TYPE_RAM|EM_ZCL_ATTRIBUTE_ACCESS_READABLE|EM_ZCL_ATTRIBUTE_DATA_DEFAULT|EM_ZCL_ATTRIBUTE_DATA_ANALOG, 36, 9, 2, EMBER_ZCLIP_TYPE_UNSIGNED_INTEGER},
};

// -----------------------------------------------------------------------------
// Commands.

// Command entries.
const EmZclCommandEntry_t emZclCommandTable[] = {
  {&emberZclClusterOtaBootloadClientSpec, EMBER_ZCL_CLUSTER_OTA_BOOTLOAD_CLIENT_COMMAND_IMAGE_NOTIFY, emZclClusterOtaBootloadClientCommandImageNotifyRequestSpec, (EmZclRequestHandler)emberZclClusterOtaBootloadClientCommandImageNotifyRequestHandler},
  {&emberZclClusterBasicServerSpec, EMBER_ZCL_CLUSTER_BASIC_SERVER_COMMAND_RESET_TO_FACTORY_DEFAULTS, emZclClusterBasicServerCommandResetToFactoryDefaultsRequestSpec, (EmZclRequestHandler)emberZclClusterBasicServerCommandResetToFactoryDefaultsRequestHandler},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_IDENTIFY, emZclClusterIdentifyServerCommandIdentifyRequestSpec, (EmZclRequestHandler)emberZclClusterIdentifyServerCommandIdentifyRequestHandler},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_IDENTIFY_QUERY, emZclClusterIdentifyServerCommandIdentifyQueryRequestSpec, (EmZclRequestHandler)emberZclClusterIdentifyServerCommandIdentifyQueryRequestHandler},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_E_Z_MODE_INVOKE, emZclClusterIdentifyServerCommandEZModeInvokeRequestSpec, (EmZclRequestHandler)emberZclClusterIdentifyServerCommandEZModeInvokeRequestHandler},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_UPDATE_COMMISSION_STATE, emZclClusterIdentifyServerCommandUpdateCommissionStateRequestSpec, (EmZclRequestHandler)emberZclClusterIdentifyServerCommandUpdateCommissionStateRequestHandler},
  {&emberZclClusterIdentifyServerSpec, EMBER_ZCL_CLUSTER_IDENTIFY_SERVER_COMMAND_TRIGGER_EFFECT, emZclClusterIdentifyServerCommandTriggerEffectRequestSpec, (EmZclRequestHandler)emberZclClusterIdentifyServerCommandTriggerEffectRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_OFF, emZclClusterOnOffServerCommandOffRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandOffRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON, emZclClusterOnOffServerCommandOnRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandOnRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_TOGGLE, emZclClusterOnOffServerCommandToggleRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandToggleRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_OFF_WITH_EFFECT, emZclClusterOnOffServerCommandOffWithEffectRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandOffWithEffectRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON_WITH_RECALL_GLOBAL_SCENE, emZclClusterOnOffServerCommandOnWithRecallGlobalSceneRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandOnWithRecallGlobalSceneRequestHandler},
  {&emberZclClusterOnOffServerSpec, EMBER_ZCL_CLUSTER_ON_OFF_SERVER_COMMAND_ON_WITH_TIMED_OFF, emZclClusterOnOffServerCommandOnWithTimedOffRequestSpec, (EmZclRequestHandler)emberZclClusterOnOffServerCommandOnWithTimedOffRequestHandler},
};
const size_t emZclCommandCount = COUNTOF(emZclCommandTable);
