// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Generated events.
#include PLATFORM_HEADER
#include "stack/include/ember-types.h"
#include "hal/hal.h"


void stateEventHandler(void);
extern EmberEventControl stateEventControl;

void updateDisplayEventHandler(void);
extern EmberEventControl updateDisplayEventControl;

void ezModeEventHandler(void);
extern EmberEventControl ezModeEventControl;

void temperatureMeasurementServerReadEventHandler(void);
extern EmberEventControl temperatureReadControl;

void emConnectionManagerNetworkStateEventHandler(void);
extern EmberEventControl emConnectionManagerNetworkStateEventControl;

void emConnectionManagerOrphanEventHandler(void);
extern EmberEventControl emConnectionManagerOrphanEventControl;

void emConnectionManagerOkToLongPollHandler(void);
extern EmberEventControl emConnectionManagerOkToLongPollEventControl;

void emZclIdentifyServerEventHandler(void);
extern EmberEventControl emZclIdentifyServerEventControl;

void emZclOtaBootloadClientEventHandler(void);
extern EmberEventControl emZclOtaBootloadClientEventControl;

void emZclOtaBootloadStorageEepromEraseEventHandler(void);
extern EmberEventControl emZclOtaBootloadStorageEepromEraseEventControl;

void emZclEzModeEventHandler(void);
extern EmberEventControl emZclEzModeEventControl;



const EmberEventData emAppEvents[] = {
  {&stateEventControl, stateEventHandler},
  {&updateDisplayEventControl, updateDisplayEventHandler},
  {&ezModeEventControl, ezModeEventHandler},
  {&temperatureReadControl, temperatureMeasurementServerReadEventHandler},
  {&emConnectionManagerNetworkStateEventControl, emConnectionManagerNetworkStateEventHandler},
  {&emConnectionManagerOrphanEventControl, emConnectionManagerOrphanEventHandler},
  {&emConnectionManagerOkToLongPollEventControl, emConnectionManagerOkToLongPollHandler},
  {&emZclIdentifyServerEventControl, emZclIdentifyServerEventHandler},
  {&emZclOtaBootloadClientEventControl, emZclOtaBootloadClientEventHandler},
  {&emZclOtaBootloadStorageEepromEraseEventControl, emZclOtaBootloadStorageEepromEraseEventHandler},
  {&emZclEzModeEventControl, emZclEzModeEventHandler},
  {NULL, NULL}
};
