// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef SILABS_THREAD_CONFIG
#define SILABS_THREAD_CONFIG

// Top level macros
#define EMBER_AF_DEVICE_NAME "smartbadge"



// Generated setup headers that are included automatically
#include "thread-debug-print.h"


// Generated plugin macros

// Use this macro to check if ADC plugin is included
#define EMBER_AF_PLUGIN_ADC

// Use this macro to check if Address Configuration Debug plugin is included
#define EMBER_AF_PLUGIN_ADDRESS_CONFIGURATION_DEBUG

// Use this macro to check if Antenna Stub plugin is included
#define EMBER_AF_PLUGIN_ANTENNA_STUB

// Use this macro to check if Basic Server plugin is included
#define EMBER_AF_PLUGIN_BASIC_SERVER

// Use this macro to check if CLI plugin is included
#define EMBER_AF_PLUGIN_CLI

// Use this macro to check if CoAP CLI plugin is included
#define EMBER_AF_PLUGIN_COAP_CLI

// Use this macro to check if CoAP Dispatch plugin is included
#define EMBER_AF_PLUGIN_COAP_DISPATCH

// Use this macro to check if Command Interpreter plugin is included
#define EMBER_AF_PLUGIN_COMMAND_INTERPRETER2

// Use this macro to check if Connection Manager CLI plugin is included
#define EMBER_AF_PLUGIN_CONNECTION_MANAGER_CLI

// Use this macro to check if Connection Manager: In Band Joining plugin is included
#define EMBER_AF_PLUGIN_CONNECTION_MANAGER_JIB
// User options for plugin Connection Manager: In Band Joining
#define EMBER_AF_PLUGIN_CONNECTION_MANAGER_JIB_RADIO_TX_POWER 3
#define EMBER_AF_PLUGIN_CONNECTION_MANAGER_JIB_ROLE ROUTER
#define EMBER_AF_PLUGIN_CONNECTION_MANAGER_JIB_NUM_REJOIN_ATTEMPTS 10 //TGBL  3(default)
#define EMBER_AF_PLUGIN_CONNECTION_MANAGER_JIB_ORPHAN_REJOIN_DELAY_MINUTES 1// TGBL 15 (default)

// Use this macro to check if Debug JTAG stub plugin is included
#define EMBER_AF_PLUGIN_DEBUG_CHANNEL_STUB

// Use this macro to check if Debug Print plugin is included
#define EMBER_AF_PLUGIN_DEBUG_PRINT
// User options for plugin Debug Print
#define EMBER_AF_DEBUG_PRINT_USE_PORT

// Use this macro to check if Dynamic Host Configuration Protocol (DHCP) Client plugin is included
#define EMBER_AF_PLUGIN_DHCP_CLIENT

// Use this macro to check if DHCP Library plugin is included
#define EMBER_AF_PLUGIN_DHCP_LIBRARY

// Use this macro to check if Diagnostic Stub plugin is included
#define EMBER_AF_PLUGIN_DIAGNOSTIC_STUB

// Use this macro to check if DTLS Authentication Parameters plugin is included
#define EMBER_AF_PLUGIN_DTLS_AUTH_PARAMS
// User options for plugin DTLS Authentication Parameters

// Use this macro to check if EEPROM plugin is included
#define EMBER_AF_PLUGIN_EEPROM
// User options for plugin EEPROM
#define EMBER_AF_PLUGIN_EEPROM_PARTIAL_WORD_STORAGE_COUNT 2

// Use this macro to check if HAL Library plugin is included
#define EMBER_AF_PLUGIN_HAL_LIBRARY

// Use this macro to check if ICMP CLI plugin is included
#define EMBER_AF_PLUGIN_ICMP_CLI

// Use this macro to check if ICMP Debug plugin is included
#define EMBER_AF_PLUGIN_ICMP_DEBUG

// Use this macro to check if Identify Server plugin is included
#define EMBER_AF_PLUGIN_IDENTIFY_SERVER

// Use this macro to check if Idle/Sleep plugin is included
#define EMBER_AF_PLUGIN_IDLE_SLEEP
// User options for plugin Idle/Sleep
#define EMBER_AF_PLUGIN_IDLE_SLEEP_MINIMUM_SLEEP_DURATION_MS 5

// Use this macro to check if Main plugin is included
#define EMBER_AF_PLUGIN_MAIN

// Use this macro to check if mbed TLS Cryptographic Library plugin is included
#define EMBER_AF_PLUGIN_MBEDTLS_LIBRARY

// Use this macro to check if Network Management CLI plugin is included
#define EMBER_AF_PLUGIN_NETWORK_MANAGEMENT_CLI

// Use this macro to check if On/Off Server plugin is included
#define EMBER_AF_PLUGIN_ON_OFF_SERVER

// Use this macro to check if OTA Bootload Client plugin is included
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT
// User options for plugin OTA Bootload Client
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_AUTO_START
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_BLOCK_ERROR_THRESHOLD 5
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_DISCOVER_SERVER_PERIOD_MINUTES 10
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_QUERY_NEXT_IMAGE_PERIOD_MINUTES 60

// Use this macro to check if OTA Bootload Client Policy plugin is included
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY
// User options for plugin OTA Bootload Client Policy
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_LOOKUP_TYPE EMBER_ZCL_OTA_DISCOVER
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_SCHEME_PARAMETER EMBER_ZCL_SCHEME_COAP
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_NAME {0x06, 's', 'i', 'l', 'a', 'b', 's', 0x03, 'c', 'o', 'm', 0x00}
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_NAME_LENGTH (12)
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_ADDRESS_PARAMETER {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_ADDRESS_PARAMETER_LENGTH (16)
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_PORT_PARAMETER 5683
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_UID_PARAMETER { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF }
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_UID_PARAMETER_LENGTH (32)
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_SERVER_ENDPOINT_PARAMETER 255
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_CURRENT_IMAGE_MANUFACTURER_CODE 57005
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_CURRENT_IMAGE_TYPE 43981
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_CURRENT_IMAGE_VERSION 65537
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_CURRENT_HARDWARE_VERSION 65535
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CLIENT_POLICY_DELETE_EXISTING_IMAGES_BEFORE_DOWNLOAD

// Use this macro to check if OTA Bootload Core plugin is included
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_CORE

// Use this macro to check if OTA Bootload Storage CLI plugin is included
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_STORAGE_CLI

// Use this macro to check if OTA Bootload Storage Core plugin is included
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_STORAGE_CORE

// Use this macro to check if OTA Bootload Storage EEPROM plugin is included
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_STORAGE_EEPROM
// User options for plugin OTA Bootload Storage EEPROM
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_STORAGE_EEPROM_START_ADDRESS 0
#define EMBER_AF_PLUGIN_OTA_BOOTLOAD_STORAGE_EEPROM_END_ADDRESS 204799

// Use this macro to check if RAIL Library plugin is included
#define EMBER_AF_PLUGIN_RAIL_LIBRARY

// Use this macro to check if Scan Debug plugin is included
#define EMBER_AF_PLUGIN_SCAN_DEBUG

// Use this macro to check if Serial plugin is included
#define EMBER_AF_PLUGIN_SERIAL

// Use this macro to check if Simulated EEPROM version 1 Library plugin is included
#define EMBER_AF_PLUGIN_SIM_EEPROM1
// User options for plugin Simulated EEPROM version 1 Library

// Use this macro to check if Stateless Address Autoconfiguration (SLAAC) Client plugin is included
#define EMBER_AF_PLUGIN_SLAAC_CLIENT

// Use this macro to check if Thread Stack Library with Silicon Labs TLS support plugin is included
#define EMBER_AF_PLUGIN_THREAD_STACK

// Use this macro to check if Version Debug plugin is included
#define EMBER_AF_PLUGIN_VERSION_DEBUG

// Use this macro to check if ZCL Core plugin is included
#define EMBER_AF_PLUGIN_ZCL_CORE
// User options for plugin ZCL Core
#define EMBER_ZCL_BINDING_TABLE_SIZE 8
#define EMBER_ZCL_CACHE_TABLE_SIZE 8
#define EMBER_ZCL_GROUP_TABLE_SIZE 4
#define EMBER_ZCL_REPORTING_CONFIGURATIONS_TABLE_SIZE 4

// Use this macro to check if ZCL Core CLI plugin is included
#define EMBER_AF_PLUGIN_ZCL_CORE_CLI


// Generated API headers

// API adc-cortexm3 from ADC plugin
#define EMBER_AF_API_ADC_CORTEXM3 "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/plugin/adc/adc-cortexm3.h"

// API adc from ADC plugin
#define EMBER_AF_API_ADC "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/plugin/adc/adc.h"

// API antenna from Antenna Stub plugin
#define EMBER_AF_API_ANTENNA "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/plugin/antenna/antenna.h"

// API coap-dispatch from CoAP Dispatch plugin
#define EMBER_AF_API_COAP_DISPATCH "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/app/thread/plugin/coap-dispatch/coap-dispatch.h"

// API command-interpreter2 from Command Interpreter plugin
#define EMBER_AF_API_COMMAND_INTERPRETER2 "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/app/util/serial/command-interpreter2.h"

// API connection-manager from Connection Manager: In Band Joining plugin
#define EMBER_AF_API_CONNECTION_MANAGER "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/app/thread/plugin/connection-manager/connection-manager.h"

// API connection-manager-jib from Connection Manager: In Band Joining plugin
#define EMBER_AF_API_CONNECTION_MANAGER_JIB "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/app/thread/plugin/connection-manager/connection-manager-jib/connection-manager-jib.h"

// API debug-print from Debug Print plugin
#define EMBER_AF_API_DEBUG_PRINT "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/app/thread/plugin/debug-print/debug-print.h"

// API diagnostic from Diagnostic Stub plugin
#define EMBER_AF_API_DIAGNOSTIC "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/micro/diagnostic.h"

// API eeprom from EEPROM plugin
#define EMBER_AF_API_EEPROM "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/util/plugin/plugin-common/eeprom/eeprom.h"

// API eeprom-print from EEPROM plugin
#define EMBER_AF_API_EEPROM_PRINT "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/util/plugin/plugin-afv6/eeprom/eeprom-print.h"

// API crc from HAL Library plugin
#define EMBER_AF_API_CRC "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/micro/crc.h"

// API endian from HAL Library plugin
#define EMBER_AF_API_ENDIAN "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/micro/endian.h"

// API hal from HAL Library plugin
#define EMBER_AF_API_HAL "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/hal.h"

// API random from HAL Library plugin
#define EMBER_AF_API_RANDOM "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/micro/random.h"

// API system-timer from HAL Library plugin
#define EMBER_AF_API_SYSTEM_TIMER "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/micro/system-timer.h"

// API token-cortexm3 from HAL Library plugin
#define EMBER_AF_API_TOKEN_CORTEXM3 "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/micro/cortexm3/token.h"

// API token from HAL Library plugin
#define EMBER_AF_API_TOKEN "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/micro/token.h"

// API zcl-ota-bootload-client from OTA Bootload Client plugin
#define EMBER_AF_API_ZCL_OTA_BOOTLOAD_CLIENT "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/app/thread/plugin/zcl/ota-bootload-client/ota-bootload-client.h"

// API zcl-ota-bootload-core from OTA Bootload Core plugin
#define EMBER_AF_API_ZCL_OTA_BOOTLOAD_CORE "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/app/thread/plugin/zcl/ota-bootload-core/ota-bootload-core.h"

// API zcl-ota-bootload-storage-core from OTA Bootload Storage Core plugin
#define EMBER_AF_API_ZCL_OTA_BOOTLOAD_STORAGE_CORE "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/app/thread/plugin/zcl/ota-bootload-storage-core/ota-bootload-storage-core.h"

// API rail-library from RAIL Library plugin
#define EMBER_AF_API_RAIL_LIBRARY "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/radio/rail_lib/common/rail.h"

// API serial from Serial plugin
#define EMBER_AF_API_SERIAL "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/plugin/serial/serial.h"

// API sim-eeprom from Simulated EEPROM version 1 Library plugin
#define EMBER_AF_API_SIM_EEPROM "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/platform/base/hal/plugin/sim-eeprom/sim-eeprom.h"

// API buffer-management from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_BUFFER_MANAGEMENT "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/framework/buffer-management.h"

// API buffer-queue from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_BUFFER_QUEUE "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/framework/buffer-queue.h"

// API child from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_CHILD "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/include/child.h"

// API coap-diagnostic from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_COAP_DIAGNOSTIC "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/include/coap-diagnostic.h"

// API coap from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_COAP "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/include/coap.h"

// API event-queue from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_EVENT_QUEUE "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/framework/event-queue.h"

// API event from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_EVENT "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/include/event.h"

// API icmp from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_ICMP "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/include/icmp.h"

// API network-management from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_NETWORK_MANAGEMENT "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/include/network-management.h"

// API stack-info from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_STACK_INFO "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/include/stack-info.h"

// API stack from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_STACK "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/include/ember.h"

// API tcp from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_TCP "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/include/tcp.h"

// API udp-peer from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_UDP_PEER "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/include/udp-peer.h"

// API udp from Thread Stack Library with Silicon Labs TLS support plugin
#define EMBER_AF_API_UDP "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/stack/include/udp.h"

// API zcl-core from ZCL Core plugin
#define EMBER_AF_API_ZCL_CORE "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/app/thread/plugin/zcl/zcl-core/zcl-core.h"

// API zcl-core-well-known from ZCL Core plugin
#define EMBER_AF_API_ZCL_CORE_WELL_KNOWN "../../../../../SiliconLabs/SimplicityStudio/v4/developer/sdks/gecko_sdk_suite/v2.1/protocol/thread_2.5/app/thread/plugin/zcl/zcl-core/zcl-core-well-known.h"


// Coap Dispatch macros
#ifdef EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH
#undef EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH
#endif
#define EMBER_AF_COAP_DISPATCH_MAX_URI_PATH_LENGTH 13


// Custom macros
#ifdef EMBER_AF_RADIO
#undef EMBER_AF_RADIO
#endif
#define EMBER_AF_RADIO EFR32

#ifdef EMBER_AF_RADIO_FULL
#undef EMBER_AF_RADIO_FULL
#endif
#define EMBER_AF_RADIO_FULL EFR32MG13P732F512GM48

#ifdef EMBER_AF_RADIO_FAMILY
#undef EMBER_AF_RADIO_FAMILY
#endif
#define EMBER_AF_RADIO_FAMILY M

#ifdef EMBER_AF_RADIO_SERIES
#undef EMBER_AF_RADIO_SERIES
#endif
#define EMBER_AF_RADIO_SERIES 1

#ifdef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#undef EMBER_AF_RADIO_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_RADIO_DEVICE_CONFIGURATION 3

#ifdef EMBER_AF_RADIO_PERFORMANCE
#undef EMBER_AF_RADIO_PERFORMANCE
#endif
#define EMBER_AF_RADIO_PERFORMANCE P

#ifdef EMBER_AF_RADIO_RADIO
#undef EMBER_AF_RADIO_RADIO
#endif
#define EMBER_AF_RADIO_RADIO 732

#ifdef EMBER_AF_RADIO_FLASH
#undef EMBER_AF_RADIO_FLASH
#endif
#define EMBER_AF_RADIO_FLASH 512K

#ifdef EMBER_AF_RADIO_TEMP
#undef EMBER_AF_RADIO_TEMP
#endif
#define EMBER_AF_RADIO_TEMP G

#ifdef EMBER_AF_RADIO_PACKAGE
#undef EMBER_AF_RADIO_PACKAGE
#endif
#define EMBER_AF_RADIO_PACKAGE M

#ifdef EMBER_AF_RADIO_PINS
#undef EMBER_AF_RADIO_PINS
#endif
#define EMBER_AF_RADIO_PINS 48

#ifdef EMBER_AF_MCU
#undef EMBER_AF_MCU
#endif
#define EMBER_AF_MCU EFR32

#ifdef EMBER_AF_MCU_FULL
#undef EMBER_AF_MCU_FULL
#endif
#define EMBER_AF_MCU_FULL EFR32MG13P732F512GM48

#ifdef EMBER_AF_MCU_FAMILY
#undef EMBER_AF_MCU_FAMILY
#endif
#define EMBER_AF_MCU_FAMILY M

#ifdef EMBER_AF_MCU_SERIES
#undef EMBER_AF_MCU_SERIES
#endif
#define EMBER_AF_MCU_SERIES 1

#ifdef EMBER_AF_MCU_DEVICE_CONFIGURATION
#undef EMBER_AF_MCU_DEVICE_CONFIGURATION
#endif
#define EMBER_AF_MCU_DEVICE_CONFIGURATION 3

#ifdef EMBER_AF_MCU_PERFORMANCE
#undef EMBER_AF_MCU_PERFORMANCE
#endif
#define EMBER_AF_MCU_PERFORMANCE P

#ifdef EMBER_AF_MCU_RADIO
#undef EMBER_AF_MCU_RADIO
#endif
#define EMBER_AF_MCU_RADIO 732

#ifdef EMBER_AF_MCU_FLASH
#undef EMBER_AF_MCU_FLASH
#endif
#define EMBER_AF_MCU_FLASH 512K

#ifdef EMBER_AF_MCU_TEMP
#undef EMBER_AF_MCU_TEMP
#endif
#define EMBER_AF_MCU_TEMP G

#ifdef EMBER_AF_MCU_PACKAGE
#undef EMBER_AF_MCU_PACKAGE
#endif
#define EMBER_AF_MCU_PACKAGE M

#ifdef EMBER_AF_MCU_PINS
#undef EMBER_AF_MCU_PINS
#endif
#define EMBER_AF_MCU_PINS 48

#ifdef EMBER_AF_BOARD_TYPE
#undef EMBER_AF_BOARD_TYPE
#endif
#define EMBER_AF_BOARD_TYPE BRD4168A

#endif // SILABS_THREAD_CONFIG
